const express = require("express");
const router = express.Router();
const editBlogController = require("../../app/controllers/EditBlog/index");
const blogController = require("../../app/controllers/Blog/blogController");
router.get("/:id/edit", editBlogController.selectBlog);
router.put("/:id/blog-id", editBlogController.postBlog);
router.put("/:id/update-save", editBlogController.saveBlog);
router.get("/getBlog/:id", editBlogController.selectBlogUser);
router.delete("/:id/delete", editBlogController.deleteBlog);
router.get("/pageBlog", blogController.index);
router.get("/readBlog", blogController.selectBlogusers);
router.get("/SameBlog", blogController.sameBlog);
router.post("/report", blogController.report);
router.get("/getReport", blogController.getReport);
router.post("/comment", blogController.comment);
router.get("/comments/:id", blogController.comments);
router.get("/getAllCmt", blogController.getAllCmt);
router.delete("/deleteComment/:id", blogController.deleteComment);
router.put("/UpdateCmt/:id", blogController.UpdateCmt);
router.get("/comments/count/:id", blogController.countCmt);
module.exports = router;
